name: Workflow 2
  on:
      push:
          branches:
              - main

  jobs:
      test:
          runs-on: ubuntu-latest
  steps:
      - name: Run tests
  run: echo "Running tests on branch main"
      